// Dev only mock Works (PLAN.md 2.3 shape). Loaded by api.js when the API is unreachable in dev.
// Covers are neutral placeholder frames, never stock photos.

function frame(n) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 1067"><rect width="1600" height="1067" fill="#1A1A1C"/><text x="800" y="548" text-anchor="middle" fill="#8C8A85" font-family="JetBrains Mono, monospace" font-size="56" letter-spacing="8">FR ${String(n).padStart(3, '0')}</text></svg>`
  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}

export const mockWorks = [
  {
    id: 1,
    slug: 'coastline-edit',
    type: 'video',
    title: 'Coastline edit',
    summary: 'A short travel edit cut to music. Placeholder entry for development.',
    body: '## Notes\n\nShot handheld over two mornings, graded for soft contrast.\n\n* Edit: Final Cut Pro\n* Grade: two node look',
    cover_url: frame(1),
    media: [{ kind: 'embed', url: 'https://www.youtube-nocookie.com/embed/aqz-KE-bpKQ' }],
    links: [{ label: 'Watch on YouTube', url: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ' }],
    tags: ['travel', 'edit'],
    shot_on: 'SONY FX3',
    date: '2026-01-31',
    published: true,
    created_at: '2026-01-31T09:00:00.000Z',
  },
  {
    id: 2,
    slug: 'studio-portraits',
    type: 'photo',
    title: 'Studio portraits',
    summary: 'A set of portraits with one key light. Placeholder entry for development.',
    body: 'One light, one backdrop, twelve frames.',
    cover_url: frame(2),
    media: [
      { kind: 'image', url: frame(3), thumb_url: frame(3), alt: 'Placeholder frame 3' },
      { kind: 'image', url: frame(4), thumb_url: frame(4), alt: 'Placeholder frame 4' },
      { kind: 'image', url: frame(5), thumb_url: frame(5), alt: 'Placeholder frame 5' },
    ],
    links: [],
    tags: ['portrait', 'studio'],
    shot_on: 'SONY A7 IV',
    date: '2025-11-12',
    published: true,
    created_at: '2025-11-12T09:00:00.000Z',
  },
  {
    id: 3,
    slug: 'self-hosted-works-feed',
    type: 'project',
    title: 'Self hosted works feed',
    summary: 'The backend behind this feed: Express, PostgreSQL and MinIO on one box.',
    body: '## Stack\n\nExpress, PostgreSQL, MinIO, sharp, Caddy, Docker Compose.\n\nImages are resized to webp on upload.',
    cover_url: frame(6),
    media: [],
    links: [{ label: 'GitHub', url: 'https://github.com/joseandreaslie' }],
    tags: ['backend', 'devops'],
    shot_on: null,
    date: '2026-02-14',
    published: true,
    created_at: '2026-02-14T09:00:00.000Z',
  },
  {
    id: 4,
    slug: 'notes-on-shipping',
    type: 'writing',
    title: 'Notes on shipping small',
    summary: 'Why small releases beat big ones. Placeholder entry for development.',
    body: '# Notes on shipping small\n\nShip the smallest thing that works, then **watch it** in production.',
    cover_url: frame(7),
    media: [],
    links: [],
    tags: ['process'],
    shot_on: null,
    date: '2025-09-03',
    published: true,
    created_at: '2025-09-03T09:00:00.000Z',
  },
  {
    id: 5,
    slug: 'draft-night-walk',
    type: 'photo',
    title: 'Night walk (draft)',
    summary: 'Unpublished draft, hidden from public lists.',
    body: '',
    cover_url: frame(8),
    media: [],
    links: [],
    tags: [],
    shot_on: 'SONY FX3',
    date: '2026-03-01',
    published: false,
    created_at: '2026-03-01T09:00:00.000Z',
  },
]
